# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sVva0NDvCb4qD8ay66J2Glkw3xz1brmI
"""

import streamlit as st
import pandas as pd
import pickle
import matplotlib.pyplot as plt

with open('arima_model.pkl', 'rb') as file:
    model = pickle.load(file)

data = pd.read_csv('supermarket_sales - Sheet1.csv', parse_dates=['Date'], index_col='Date')
data = data.resample('D').sum()

st.title("Sales Forecasting with ARIMA")
st.markdown("""
This app predicts daily sales using an ARIMA model.
Upload your dataset or view the forecast for future dates.
""")

st.subheader("Historical Sales Data")
st.line_chart(data['Total'])

st.subheader("Future Sales Forecast")
steps = st.slider("Select number of days to forecast", min_value=1, max_value=30, value=7)

future_forecast = model.forecast(steps=steps)
future_dates = pd.date_range(start=data.index[-1], periods=steps + 1, freq='D')[1:]

forecast_df = pd.DataFrame({
    'Date': future_dates,
    'Forecasted Sales': future_forecast
})
st.write(forecast_df)

st.line_chart(forecast_df.set_index('Date'))